version: "3.9"

services:
  api:
    image: ghcr.io/ka7eh/ctsm-api:${API_VERSION:-latest}
    restart: unless-stopped
    entrypoint: /ctsm-api/docker/entrypoint_api.sh
    environment:
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
      - SKIP_CTSM_CHECKS=0
    networks:
      - default
    ports:
      - ${PORT:-8000}:8000
    volumes:
      - ./docker/api/entrypoint_api.sh:/ctsm-api/docker/entrypoint_api.sh
      - ./docker/api/.env:/ctsm-api/.env
      - ./resources:/ctsm-api/resources

  tasks:
    image: ghcr.io/ka7eh/ctsm-api:${API_VERSION:-latest}
    restart: unless-stopped
    entrypoint: /ctsm-api/docker/entrypoint_tasks.sh
    environment:
      - HOST_USER=${HOST_USER}
      - HOST_UID=${HOST_UID}
    networks:
      - default
    volumes:
      - ./docker/api/.env:/ctsm-api/.env
      - ./resources:/ctsm-api/resources

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - default
  
  ui:
    image: ghcr.io/ka7eh/fates-platform:${PLATFORM_VERSION:-latest}
    restart: unless-stopped
    ports:
      - ${PORT:-8080}:80
  
  jupyter:
    build:
      context: docker/jupyter
      dockerfile: Dockerfile
    restart: unless-stopped
    user: root
    environment:
      - NB_USER=${HOST_USER:-jovyan}
      - NB_UID=${HOST_UID:-1000}
      - NB_GID=${HOST_GID:-100}
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
    working_dir: /home/${HOST_USER:-jovyan}
    ports:
      - ${PORT:-8888}:8888
    volumes:
      - ./notebooks:/home/${HOST_USER:-jovyan}/notebooks
      - ./resources/cases:/home/${HOST_USER:-jovyan}/cases
      - ./resources/data:/home/${HOST_USER:-jovyan}/data

networks:
  default:
